name: build docker images
on:
  push:
    branches:
      - main
jobs:
  build-docker:
    strategy:
      matrix:
        arch: [x86_64, aarch64]

    runs-on: ubuntu-latest
    steps:
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@master

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.12.0pre20221005_ac0fb38/install
          # Configure Nix to enable flakes
          extra_nix_config: |
            extra-platforms = aarch64-linux
            experimental-features = nix-command flakes

      - name: Register binfmt
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Test binfmt availability
        run: |
          cat /proc/sys/fs/binfmt_misc/qemu-aarch64

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0

      - name: build docker image
        run: |
          nix build .#packages.${{ matrix.arch }}-linux.docker-image
          docker load < result

      - name: execute docker image
        run: |
          docker run --rm mayniki/shelly-exporter:latest shelly-exporter -h

      - name: push docker image
        run: |
          docker tag mayniki/shelly-exporter:latest mayniki/shelly-exporter:${{ matrix.arch }}-latest
          docker push mayniki/shelly-exporter:${{ matrix.arch }}-latest

  manifest-create:
    needs: [build-docker]
    runs-on: ubuntu-latest
    steps:
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@master

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: create manifest
        run: |
          docker manifest create \
          mayniki/shelly-exporter:latest \
          --amend mayniki/shelly-exporter:x86_64-latest \
          --amend mayniki/shelly-exporter:aarch64-latest

      - name: push manifest
        run: |
          docker manifest push mayniki/shelly-exporter:latest
